### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by ValentinGlaser** [MrLight/pytebis#2]
**BUG**: pytebis currently not compatible with newest `numpy` version

![image](https://github.com/MrLight/pytebis/assets/86845720/02f7c02e-11fa-4228-bdb2-bf1875339bc2)

- [ ]  change np.float to either float by itself or np.float64

**Comment by MrLight** [comment]
see #3

**Comment by MrLight** [comment]
fixed new pypi version available
